-- 즐겨찾기가 가장 많은 식당 정보 출력하기
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE FAVORITES IN (
    SELECT MAX(FAVORITES)
    FROM REST_INFO
    GROUP BY FOOD_TYPE)
-- 이름에 관계없이 첫 번째 열로 그룹화하는 것을 의미
GROUP BY 1
ORDER BY FOOD_TYPE DESC;