-- 카테고리 별 도서 판매량 집계하기
SELECT T1.CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK AS T1
INNER JOIN BOOK_SALES AS T2
    ON T1.BOOK_ID = T2.BOOK_ID
WHERE DATE_FORMAT(T2.SALES_DATE,'%Y-%m') = '2022-01'
GROUP BY T1.CATEGORY
ORDER BY T1.CATEGORY;