-- 대여 기록이 존재하는 자동차 리스트 구하기
SELECT T1.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS T1
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS T2
    ON T1.CAR_ID = T2.CAR_ID
WHERE CAR_TYPE = '세단'
    AND DATE_FORMAT(START_DATE, '%Y-%m') = '2022-10'
GROUP BY CAR_ID
ORDER BY T1.CAR_ID DESC, 1;