-- 서울에 위치한 식당 목록 출력하기
SELECT T2.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS T1
INNER JOIN REST_REVIEW AS T2
    ON T1.REST_ID = T2.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY T2.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;